# Analyzing Tune Experiment Results
The content in this notebook uses the [Analyzing Tune Experiment Results](https://docs.ray.io/en/latest/tune/examples/tune_analyze_results.html?highlight=results%20json#analyzing-tune-experiment-results) section of the Ray docs. See the link for more details.

In [1]:
import os

import pandas as pd

import ray
from ray import tune

/home/afennelly/miniconda3/envs/sh2/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-11-14 13:33:03,787	INFO util.py:159 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2023-11-14 13:33:04,077	INFO util.py:159 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [2]:
os.environ["PATH"] = ":".join([os.environ["PATH"], f"{os.environ['HOME']}/simharness2"])

In [3]:
EXPERIMENT_DIR = "/data/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN"
TRIAL_DIR = "/data/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN/DQN_simharness2.environments.reactive_bench_sarl.ReactiveHarness_b015d_00000_0_2023-11-13_02-09-35"

## Experiment-level Analysis: Working with `ResultGrid`

In [4]:
print(f"Loading results from {EXPERIMENT_DIR}...")
restored_tuner = tune.Tuner.restore(EXPERIMENT_DIR, trainable="DQN")

result_grid = restored_tuner.get_results()

Loading results from /data/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN...

2023-11-14 13:33:05,084	INFO experiment_analysis.py:972 -- No trial data passed in during `ExperimentAnalysis` initialization -- you are most likely loading the experiment after it has completed.
Loading trial data from the experiment checkpoint file. This may result in loading some stale information, since checkpointing is periodic.
/home/afennelly/miniconda3/envs/sh2/lib/python3.9/site-packages/ray/tune/utils/serialization.py:43: UserWarning: This figure was saved with matplotlib version 3.8.1 and is unlikely to function correctly.
  return cloudpickle.loads(hex_to_binary(obj["value"]))
2023-11-14 13:33:06,964	WARNING deprecation.py:50 -- DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
/home/afennelly/miniconda3/envs/sh2/lib/python3.9/site-packages/ray/tune/utils/serialization.py:43: UserWarning: This figure was saved with matplotlib version 3.8.1 and is unlikely to function correctly.
  return cloudpickle.loads(hex_to_binary(obj["value"]))

In [5]:
results_df = result_grid.get_dataframe()
results_df

,episode_reward_max,episode_reward_min,episode_reward_mean,episode_len_mean,episodes_this_iter,num_faulty_episodes,num_healthy_workers,num_in_flight_async_reqs,num_remote_worker_restarts,num_agent_steps_sampled,...,config/evaluation_config/env_config/interactions,config/evaluation_config/env_config/is_evaluation_env,config/evaluation_config/env_config/movements,config/evaluation_config/env_config/normalized_attributes,config/evaluation_config/env_config/randomize_initial_agent_pos,config/evaluation_config/env_config/reward_cls_partial,config/evaluation_config/env_config/sim,config/tf_session_args/device_count/CPU,config/tf_session_args/gpu_options/allow_growth,logdir
0,0.018906,-2.583333,-0.194426,520.68,8,0,8,0,0,9708168,...,[fireline],True,"[up, down, left, right]",[],False,functools.partial(<class 'simharness2.rewards....,<simfire.sim.simulation.FireSimulation object ...,1,True,/data/lslab2/fireline/simharness/experiments/2...

## Trial-level Analysis: Working with an individual `Result`

In [6]:
from ray.air import Result

# Get the best result
best_result: Result = result_grid.get_best_result()

In [7]:
best_result

Result(
  metrics={'evaluation': {'sampler_results': {'episode_reward_max': -0.0019712976386416585, 'episode_reward_min': -0.0019712976386416585, 'episode_reward_mean': -0.0019712976386416585, 'episode_len_mean': 865.0, 'episode_media': {'gif_data': [{'path': '/nfs/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN/DQN_simharness2.environments.reactive_bench_sarl.ReactiveHarness_b015d_00000_0_2023-11-13_02-09-35/gifs/eval_iter_20.gif', 'name': 'operational_lat_36.09493_lon_-120.52193', 'step': 20, 'context': {'fire_initial_position': [69, 5]}}]}, 'episodes_this_iter': 1, 'policy_reward_min': {}, 'policy_reward_max': {}, 'policy_reward_mean': {}, 'custom_metrics': {'movement_mean': 0.0, 'movement_min': 0, 'movement_max': 0, 'interaction_mean': 0.0, 'interaction_min': 0, 'interaction_max': 0, 'moved_off_map_mean': 1.0, 'moved_off_map_min': 1, 'moved_off_map_max': 1, 'near_fire_mean': 0.0, 'near_fire_min': 0, 'near_fire_max': 0, 'burn_status_mean': 3.0, 'burn_status_min': 3, 'burn_status_max': 3, 'sim/burned_mean': 10081.0, 'sim/burned_min': 10081, 'sim/burned_max': 10081, 'sim/unburned_mean': 6238.0, 'sim/unburned_min': 6238, 'sim/unburned_max': 6238, 'sim/burning_mean': 0.0, 'sim/burning_min': 0, 'sim/burning_max': 0, 'sim/burn_rate_mean': 11.654335260115607, 'sim/burn_rate_min': 11.654335260115607, 'sim/burn_rate_max': 11.654335260115607, 'mitigated_mean': 65.0, 'mitigated_min': 65, 'mitigated_max': 65, 'agent_interactions_mean': 4.0, 'agent_interactions_min': 4, 'agent_interactions_max': 4, 'agent_movements_mean': 4.0, 'agent_movements_min': 4, 'agent_movements_max': 4, 'area_saved_mean': -11.0, 'area_saved_min': -11, 'area_saved_max': -11, 'area_saved_prop_mean': -0.001085347804637395, 'area_saved_prop_min': -0.001085347804637395, 'area_saved_prop_max': -0.001085347804637395, 'burn_rate_reduction_mean': 0.062427745664740186, 'burn_rate_reduction_min': 0.062427745664740186, 'burn_rate_reduction_max': 0.062427745664740186, 'bench_episode_length_mean': 864.0, 'bench_episode_length_min': 864, 'bench_episode_length_max': 864, 'timesteps_saved_mean': -4.0, 'timesteps_saved_min': -4, 'timesteps_saved_max': -4, 'bench_sim/burned_mean': 10135.0, 'bench_sim/burned_min': 10135, 'bench_sim/burned_max': 10135, 'bench_sim/unburned_mean': 6249.0, 'bench_sim/unburned_min': 6249, 'bench_sim/unburned_max': 6249, 'bench_sim/burning_mean': 0.0, 'bench_sim/burning_min': 0, 'bench_sim/burning_max': 0, 'bench_sim/burn_rate_mean': 46.9212962962963, 'bench_sim/burn_rate_min': 46.9212962962963, 'bench_sim/burn_rate_max': 46.9212962962963}, 'hist_stats': {'episode_reward': [-0.0019712976386416585], 'episode_lengths': [865]}, 'sampler_perf': {'mean_raw_obs_processing_ms': 24.725969685361527, 'mean_inference_ms': 6.991998565486539, 'mean_action_processing_ms': 0.23215747928545194, 'mean_env_wait_ms': 33.547999277905404, 'mean_env_render_ms': 0.0}, 'num_faulty_episodes': 0, 'connector_metrics': {'ObsPreprocessorConnector_ms': 0.01373291015625, 'StateBufferConnector_ms': 0.009131431579589844, 'ViewRequirementAgentConnector_ms': 0.30515193939208984}}, 'episode_reward_max': -0.0019712976386416585, 'episode_reward_min': -0.0019712976386416585, 'episode_reward_mean': -0.0019712976386416585, 'episode_len_mean': 865.0, 'episodes_this_iter': 1, 'policy_reward_min': {}, 'policy_reward_max': {}, 'policy_reward_mean': {}, 'custom_metrics': {'movement_mean': 0.0, 'movement_min': 0, 'movement_max': 0, 'interaction_mean': 0.0, 'interaction_min': 0, 'interaction_max': 0, 'moved_off_map_mean': 1.0, 'moved_off_map_min': 1, 'moved_off_map_max': 1, 'near_fire_mean': 0.0, 'near_fire_min': 0, 'near_fire_max': 0, 'burn_status_mean': 3.0, 'burn_status_min': 3, 'burn_status_max': 3, 'sim/burned_mean': 10081.0, 'sim/burned_min': 10081, 'sim/burned_max': 10081, 'sim/unburned_mean': 6238.0, 'sim/unburned_min': 6238, 'sim/unburned_max': 6238, 'sim/burning_mean': 0.0, 'sim/burning_min': 0, 'sim/burning_max': 0, 'sim/burn_rate_mean': 11.654335260115607, 'sim/burn_rate_min': 11.654335260115607, 'sim/burn_rate_max': 11.654335260115607, 'mitigated_mean': 65.0, 'mitigated_min': 65, 'mitigated_max': 65, 'agent_interactions_mean': 4.0, 'agent_interactions_min': 4, 'agent_interactions_max': 4, 'agent_movements_mean': 4.0, 'agent_movements_min': 4, 'agent_movements_max': 4, 'area_saved_mean': -11.0, 'area_saved_min': -11, 'area_saved_max': -11, 'area_saved_prop_mean': -0.001085347804637395, 'area_saved_prop_min': -0.001085347804637395, 'area_saved_prop_max': -0.001085347804637395, 'burn_rate_reduction_mean': 0.062427745664740186, 'burn_rate_reduction_min': 0.062427745664740186, 'burn_rate_reduction_max': 0.062427745664740186, 'bench_episode_length_mean': 864.0, 'bench_episode_length_min': 864, 'bench_episode_length_max': 864, 'timesteps_saved_mean': -4.0, 'timesteps_saved_min': -4, 'timesteps_saved_max': -4, 'bench_sim/burned_mean': 10135.0, 'bench_sim/burned_min': 10135, 'bench_sim/burned_max': 10135, 'bench_sim/unburned_mean': 6249.0, 'bench_sim/unburned_min': 6249, 'bench_sim/unburned_max': 6249, 'bench_sim/burning_mean': 0.0, 'bench_sim/burning_min': 0, 'bench_sim/burning_max': 0, 'bench_sim/burn_rate_mean': 46.9212962962963, 'bench_sim/burn_rate_min': 46.9212962962963, 'bench_sim/burn_rate_max': 46.9212962962963}, 'hist_stats': {'episode_reward': [-0.0019712976386416585], 'episode_lengths': [865]}, 'sampler_perf': {'mean_raw_obs_processing_ms': 24.725969685361527, 'mean_inference_ms': 6.991998565486539, 'mean_action_processing_ms': 0.23215747928545194, 'mean_env_wait_ms': 33.547999277905404, 'mean_env_render_ms': 0.0}, 'num_faulty_episodes': 0, 'connector_metrics': {'ObsPreprocessorConnector_ms': 0.01373291015625, 'StateBufferConnector_ms': 0.009131431579589844, 'ViewRequirementAgentConnector_ms': 0.30515193939208984}, 'num_agent_steps_sampled_this_iter': 865, 'num_env_steps_sampled_this_iter': 865, 'timesteps_this_iter': 865, 'num_healthy_workers': 1, 'num_in_flight_async_reqs': 0, 'num_remote_worker_restarts': 0}, 'custom_metrics': {'movement_mean': 0.67, 'movement_min': 0, 'movement_max': 3, 'interaction_mean': 0.0, 'interaction_min': 0, 'interaction_max': 0, 'moved_off_map_mean': 1.0, 'moved_off_map_min': 1, 'moved_off_map_max': 1, 'near_fire_mean': 0.0, 'near_fire_min': 0, 'near_fire_max': 0, 'burn_status_mean': 2.93, 'burn_status_min': 2, 'burn_status_max': 3, 'sim/burned_mean': 9262.93, 'sim/burned_min': 1, 'sim/burned_max': 14079, 'sim/unburned_mean': 7062.27, 'sim/unburned_min': 2236, 'sim/unburned_max': 16382, 'sim/burning_mean': 0.0, 'sim/burning_min': 0, 'sim/burning_max': 0, 'sim/burn_rate_mean': 16.972509594984892, 'sim/burn_rate_min': 0.058823529411764705, 'sim/burn_rate_max': 24.18013856812933, 'mitigated_mean': 58.8, 'mitigated_min': 1, 'mitigated_max': 75, 'agent_interactions_mean': 4.0, 'agent_interactions_min': 4, 'agent_interactions_max': 4, 'agent_movements_mean': 4.0, 'agent_movements_min': 4, 'agent_movements_max': 4, 'area_saved_mean': -3.93, 'area_saved_min': -17, 'area_saved_max': 60, 'area_saved_prop_mean': -0.14040581077367945, 'area_saved_prop_min': -2.0, 'area_saved_prop_max': 0.004244482173174873, 'burn_rate_reduction_mean': 0.09992165413384362, 'burn_rate_reduction_min': 0.0, 'burn_rate_reduction_max': 0.23556581986143144, 'bench_episode_length_mean': 523.68, 'bench_episode_length_min': 20, 'bench_episode_length_max': 816, 'timesteps_saved_mean': 0.0, 'timesteps_saved_min': 0, 'timesteps_saved_max': 0, 'bench_sim/burned_mean': 9317.8, 'bench_sim/burned_min': 1, 'bench_sim/burned_max': 14136, 'bench_sim/unburned_mean': 7066.2, 'bench_sim/unburned_min': 2248, 'bench_sim/unburned_max': 16383, 'bench_sim/burning_mean': 0.0, 'bench_sim/burning_min': 0, 'bench_sim/burning_max': 0, 'bench_sim/burn_rate_mean': 67.89699729904116, 'bench_sim/burn_rate_min': 0.2, 'bench_sim/burn_rate_max': 96.55963302752293}, 'episode_media': {}, 'info': {'learner': {'default_policy': {'custom_metrics': {}, 'learner_stats': {'cur_lr': 0.00454119}, 'model': {}, 'num_grad_updates_lifetime': 433122.0, 'diff_num_grad_updates_vs_sampler_policy': 433121.0, 'td_error': array([1.0783982 , 0.8185965 , 1.4144962 , 2.2208886 , 0.8188424 ,
       0.8837852 , 0.8229237 , 0.8277653 , 2.1164024 , 1.9642304 ,
       0.88824534, 1.8542435 , 0.8910051 , 0.8904718 , 1.6797879 ,
       1.5880364 , 0.90421224], dtype=float32), 'mean_td_error': 1.2742547778522266}}, 'num_env_steps_sampled': 9708168, 'num_env_steps_trained': 433130, 'num_agent_steps_sampled': 9708168, 'num_agent_steps_trained': 433130, 'last_target_update_ts': 9708168, 'num_target_updates': 1973}, 'sampler_results': {'episode_reward_max': 0.01890563101301639, 'episode_reward_min': -2.5833333333333335, 'episode_reward_mean': -0.19442550606742112, 'episode_len_mean': 520.68, 'episode_media': {}, 'episodes_this_iter': 8, 'policy_reward_min': {}, 'policy_reward_max': {}, 'policy_reward_mean': {}, 'custom_metrics': {'movement_mean': 0.67, 'movement_min': 0, 'movement_max': 3, 'interaction_mean': 0.0, 'interaction_min': 0, 'interaction_max': 0, 'moved_off_map_mean': 1.0, 'moved_off_map_min': 1, 'moved_off_map_max': 1, 'near_fire_mean': 0.0, 'near_fire_min': 0, 'near_fire_max': 0, 'burn_status_mean': 2.93, 'burn_status_min': 2, 'burn_status_max': 3, 'sim/burned_mean': 9262.93, 'sim/burned_min': 1, 'sim/burned_max': 14079, 'sim/unburned_mean': 7062.27, 'sim/unburned_min': 2236, 'sim/unburned_max': 16382, 'sim/burning_mean': 0.0, 'sim/burning_min': 0, 'sim/burning_max': 0, 'sim/burn_rate_mean': 16.972509594984892, 'sim/burn_rate_min': 0.058823529411764705, 'sim/burn_rate_max': 24.18013856812933, 'mitigated_mean': 58.8, 'mitigated_min': 1, 'mitigated_max': 75, 'agent_interactions_mean': 4.0, 'agent_interactions_min': 4, 'agent_interactions_max': 4, 'agent_movements_mean': 4.0, 'agent_movements_min': 4, 'agent_movements_max': 4, 'area_saved_mean': -3.93, 'area_saved_min': -17, 'area_saved_max': 60, 'area_saved_prop_mean': -0.14040581077367945, 'area_saved_prop_min': -2.0, 'area_saved_prop_max': 0.004244482173174873, 'burn_rate_reduction_mean': 0.09992165413384362, 'burn_rate_reduction_min': 0.0, 'burn_rate_reduction_max': 0.23556581986143144, 'bench_episode_length_mean': 523.68, 'bench_episode_length_min': 20, 'bench_episode_length_max': 816, 'timesteps_saved_mean': 0.0, 'timesteps_saved_min': 0, 'timesteps_saved_max': 0, 'bench_sim/burned_mean': 9317.8, 'bench_sim/burned_min': 1, 'bench_sim/burned_max': 14136, 'bench_sim/unburned_mean': 7066.2, 'bench_sim/unburned_min': 2248, 'bench_sim/unburned_max': 16383, 'bench_sim/burning_mean': 0.0, 'bench_sim/burning_min': 0, 'bench_sim/burning_max': 0, 'bench_sim/burn_rate_mean': 67.89699729904116, 'bench_sim/burn_rate_min': 0.2, 'bench_sim/burn_rate_max': 96.55963302752293}, 'hist_stats': {'episode_reward': [-0.002400316276968236, 0.01609623856319892, -0.001581384841296733, -0.004121316836553495, 0.01178977272727273, -0.004147727272727244, 0.01846590909090912, -0.003011183138395467, 0.01485795454545455, -0.0016193181818181448, -0.0017329545454544922, -0.00227272727272723, -0.0017954966744397494, -0.00257761816496758, 0.008601714550509704, -0.003763613089962663, -0.004054680259499556, -0.0027224281742354263, -0.001737720111214113, -0.004778730305838748, -0.0010332611690612005, -0.0013284786459358234, 0.000959456799842569, -0.001451485927966911, -0.0017221019484353272, -0.0012054713639047254, -0.001992717968903745, -0.0018205077740602086, -2.5833333333333335, -0.0008602711157456205, -2.0, -0.0015119916579771455, -2.5833333333333335, -0.000808133472367081, -2.5833333333333335, -0.0009893985433367303, -2.5833333333333335, 0.0013555787278414207, -2.5833333333333335, -0.000782064650677881, -2.0, 0.0009907021927379272, -2.5833333333333335, -0.0015628474620789112, -0.0018536826495304316, -0.0020514087988136548, -0.001235788433020266, -0.0019525457241720264, -0.002298566485417701, -0.0019525457241720415, -0.0017795353435491941, -0.0020514087988136513, -0.0008293296728437748, -0.0007149393731411736, 0.01121024937085336, -0.0017158544955387881, 0.010266529398307021, -0.0015728666209105639, 0.005690917410203617, -0.0013440860215053886, -0.0010611205432937247, 0.01890563101301639, -0.0010788058856819535, -0.0015916808149405827, -0.0010611205432937212, 0.007905348047538176, -0.0009903791737408104, -0.0016093661573288176, -0.0020355742346481764, -0.0027501964426030357, -0.0008214872490892093, 0.0010894247460836973, 0.012590185013215226, -0.0016251160797199704, 0.003910993642403033, 0.001678691335095369, 0.015700712589073643, -0.0018048288686047702, -0.0024940617577197, -0.002114014251781467, -0.0017575031842421533, -0.0018764845605700612, 0.014180522565320656, -0.0015676959619952326, -0.001585267274197038, -0.0010379425671780233, -0.0008937838772921248, -0.0003459808557259702, 0.0005189712835889517, -0.0014992503748126407, -0.0017293728792432317, -0.0017587360166070815, 0.0009224028594488634, -0.000922402859448868, 0.0001729505361466594, -0.00011530035743111164, -0.0006053268765133153, -0.0010953533955955282, -0.0013259541104577428, -0.0005188516084399862], 'episode_lengths': [729, 729, 729, 729, 589, 589, 589, 589, 589, 589, 589, 589, 449, 449, 449, 449, 449, 449, 449, 449, 813, 813, 813, 813, 813, 813, 813, 813, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 737, 737, 737, 737, 737, 737, 737, 737, 473, 473, 473, 473, 473, 473, 473, 473, 585, 585, 585, 585, 585, 585, 585, 585, 645, 645, 645, 645, 645, 645, 645, 645, 433, 433, 433, 433, 433, 433, 433, 433, 429, 429, 429, 429, 429, 429, 429, 429, 417, 417, 417, 417, 417, 417, 417, 417]}, 'sampler_perf': {'mean_raw_obs_processing_ms': 3.132908339797339, 'mean_inference_ms': 7.936367046684818, 'mean_action_processing_ms': 0.24758728631330015, 'mean_env_wait_ms': 29.368645848674777, 'mean_env_render_ms': 0.0}, 'num_faulty_episodes': 0, 'connector_metrics': {'ObsPreprocessorConnector_ms': 0.020465612411499023, 'StateBufferConnector_ms': 0.010177373886108398, 'ViewRequirementAgentConnector_ms': 0.3462393283843994}}, 'episode_reward_max': 0.01890563101301639, 'episode_reward_min': -2.5833333333333335, 'episode_reward_mean': -0.19442550606742112, 'episode_len_mean': 520.68, 'episodes_this_iter': 8, 'policy_reward_min': {}, 'policy_reward_max': {}, 'policy_reward_mean': {}, 'hist_stats': {'episode_reward': [-0.002400316276968236, 0.01609623856319892, -0.001581384841296733, -0.004121316836553495, 0.01178977272727273, -0.004147727272727244, 0.01846590909090912, -0.003011183138395467, 0.01485795454545455, -0.0016193181818181448, -0.0017329545454544922, -0.00227272727272723, -0.0017954966744397494, -0.00257761816496758, 0.008601714550509704, -0.003763613089962663, -0.004054680259499556, -0.0027224281742354263, -0.001737720111214113, -0.004778730305838748, -0.0010332611690612005, -0.0013284786459358234, 0.000959456799842569, -0.001451485927966911, -0.0017221019484353272, -0.0012054713639047254, -0.001992717968903745, -0.0018205077740602086, -2.5833333333333335, -0.0008602711157456205, -2.0, -0.0015119916579771455, -2.5833333333333335, -0.000808133472367081, -2.5833333333333335, -0.0009893985433367303, -2.5833333333333335, 0.0013555787278414207, -2.5833333333333335, -0.000782064650677881, -2.0, 0.0009907021927379272, -2.5833333333333335, -0.0015628474620789112, -0.0018536826495304316, -0.0020514087988136548, -0.001235788433020266, -0.0019525457241720264, -0.002298566485417701, -0.0019525457241720415, -0.0017795353435491941, -0.0020514087988136513, -0.0008293296728437748, -0.0007149393731411736, 0.01121024937085336, -0.0017158544955387881, 0.010266529398307021, -0.0015728666209105639, 0.005690917410203617, -0.0013440860215053886, -0.0010611205432937247, 0.01890563101301639, -0.0010788058856819535, -0.0015916808149405827, -0.0010611205432937212, 0.007905348047538176, -0.0009903791737408104, -0.0016093661573288176, -0.0020355742346481764, -0.0027501964426030357, -0.0008214872490892093, 0.0010894247460836973, 0.012590185013215226, -0.0016251160797199704, 0.003910993642403033, 0.001678691335095369, 0.015700712589073643, -0.0018048288686047702, -0.0024940617577197, -0.002114014251781467, -0.0017575031842421533, -0.0018764845605700612, 0.014180522565320656, -0.0015676959619952326, -0.001585267274197038, -0.0010379425671780233, -0.0008937838772921248, -0.0003459808557259702, 0.0005189712835889517, -0.0014992503748126407, -0.0017293728792432317, -0.0017587360166070815, 0.0009224028594488634, -0.000922402859448868, 0.0001729505361466594, -0.00011530035743111164, -0.0006053268765133153, -0.0010953533955955282, -0.0013259541104577428, -0.0005188516084399862], 'episode_lengths': [729, 729, 729, 729, 589, 589, 589, 589, 589, 589, 589, 589, 449, 449, 449, 449, 449, 449, 449, 449, 813, 813, 813, 813, 813, 813, 813, 813, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 17, 557, 737, 737, 737, 737, 737, 737, 737, 737, 473, 473, 473, 473, 473, 473, 473, 473, 585, 585, 585, 585, 585, 585, 585, 585, 645, 645, 645, 645, 645, 645, 645, 645, 433, 433, 433, 433, 433, 433, 433, 433, 429, 429, 429, 429, 429, 429, 429, 429, 417, 417, 417, 417, 417, 417, 417, 417]}, 'sampler_perf': {'mean_raw_obs_processing_ms': 3.132908339797339, 'mean_inference_ms': 7.936367046684818, 'mean_action_processing_ms': 0.24758728631330015, 'mean_env_wait_ms': 29.368645848674777, 'mean_env_render_ms': 0.0}, 'num_faulty_episodes': 0, 'connector_metrics': {'ObsPreprocessorConnector_ms': 0.020465612411499023, 'StateBufferConnector_ms': 0.010177373886108398, 'ViewRequirementAgentConnector_ms': 0.3462393283843994}, 'num_healthy_workers': 8, 'num_in_flight_async_reqs': 0, 'num_remote_worker_restarts': 0, 'num_agent_steps_sampled': 9708168, 'num_agent_steps_trained': 433130, 'num_env_steps_sampled': 9708168, 'num_env_steps_trained': 433130, 'num_env_steps_sampled_this_iter': 3336, 'num_env_steps_trained_this_iter': 17, 'num_env_steps_sampled_throughput_per_sec': 128.16027824235576, 'num_env_steps_trained_throughput_per_sec': 0.6530949430815491, 'num_steps_trained_this_iter': 17, 'agent_timesteps_total': 9708168, 'timers': {'training_iteration_time_ms': 35940.804, 'sample_time_ms': 26241.087, 'load_time_ms': 22.576, 'load_throughput': 9877.83, 'learn_time_ms': 8576.884, 'learn_throughput': 26.0, 'synch_weights_time_ms': 33.927}, 'counters': {'num_env_steps_sampled': 9708168, 'num_env_steps_trained': 433130, 'num_agent_steps_sampled': 9708168, 'num_agent_steps_trained': 433130, 'last_target_update_ts': 9708168, 'num_target_updates': 1973}, 'done': True, 'trial_id': 'b015d_00000', 'perf': {'cpu_util_percent': 3.906741573033708, 'ram_util_percent': 3.0528089887640455, 'gpu_util_percent0': 0.00044943820224719103, 'vram_util_percent0': 0.2529296875}, 'experiment_tag': '0'},
  path='/data/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN/DQN_simharness2.environments.reactive_bench_sarl.ReactiveHarness_b015d_00000_0_2023-11-13_02-09-35',
  checkpoint=Checkpoint(local_path=/data/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN/DQN_simharness2.environments.reactive_bench_sarl.ReactiveHarness_b015d_00000_0_2023-11-13_02-09-35/checkpoint_002000)
)

In [8]:
best_result.config

{'extra_python_environs_for_driver': {},
 'extra_python_environs_for_worker': {},
 'num_gpus': 1,
 'num_cpus_per_worker': 1,
 'num_gpus_per_worker': 0,
 '_fake_gpus': False,
 'num_learner_workers': 0,
 'num_gpus_per_learner_worker': 0,
 'num_cpus_per_learner_worker': 1,
 'local_gpu_idx': 0,
 'custom_resources_per_worker': {},
 'placement_strategy': 'PACK',
 'eager_tracing': False,
 'eager_max_retraces': 20,
 'tf_session_args': {'intra_op_parallelism_threads': 2,
  'inter_op_parallelism_threads': 2,
  'gpu_options': {'allow_growth': True},
  'log_device_placement': False,
  'device_count': {'CPU': 1},
  'allow_soft_placement': True},
 'local_tf_session_args': {'intra_op_parallelism_threads': 8,
  'inter_op_parallelism_threads': 8},
 'torch_compile_learner': False,
 'torch_compile_learner_what_to_compile': 'forward_train',
 'torch_compile_learner_dynamo_backend': 'inductor',
 'torch_compile_learner_dynamo_mode': None,
 'torch_compile_worker': False,
 'torch_compile_worker_dynamo_backend': 'onnxrt',
 'torch_compile_worker_dynamo_mode': None,
 'env': 'simharness2.environments.reactive_bench_sarl.ReactiveHarness',
 'env_config': {'sim': <simfire.sim.simulation.FireSimulation at 0x7fa7e5af93d0>,
  'movements': ['up', 'down', 'left', 'right'],
  'interactions': ['fireline'],
  'attributes': ['fire_map', 'bench_fire_map', 'bench_fire_map_final'],
  'normalized_attributes': [],
  'agent_speed': 4,
  'harness_analytics_partial': functools.partial(<class 'simharness2.analytics.harness_analytics.ReactiveHarnessAnalytics'>, sim_analytics_partial=functools.partial(<class 'simharness2.analytics.simulation_analytics.FireSimulationAnalytics'>, agent_analytics_partial=functools.partial(<class 'simharness2.analytics.agent_analytics.ReactiveAgentAnalytics'>, movement_types=['up', 'down', 'left', 'right'], interaction_types=['fireline']))),
  'reward_cls_partial': functools.partial(<class 'simharness2.rewards.base_reward.BenchFirstRewardV3'>),
  'initial_agent_pos': [64, 0],
  'randomize_initial_agent_pos': False,
  'benchmark_sim': <simfire.sim.simulation.FireSimulation at 0x7fa7e5af9bb0>,
  'action_space_partial': functools.partial(<class 'gymnasium.spaces.discrete.Discrete'>)},
 'observation_space': None,
 'action_space': None,
 'env_task_fn': None,
 'render_env': False,
 'clip_rewards': None,
 'normalize_actions': True,
 'clip_actions': False,
 'disable_env_checking': True,
 '_is_atari': False,
 'auto_wrap_old_gym_envs': True,
 'action_mask_key': 'action_mask',
 'env_runner_cls': None,
 'num_envs_per_worker': 1,
 'sample_collector': ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector,
 'sample_async': False,
 'enable_connectors': True,
 'update_worker_filter_stats': True,
 'use_worker_filter_stats': True,
 'rollout_fragment_length': 'auto',
 'batch_mode': 'complete_episodes',
 'remote_worker_envs': False,
 'remote_env_batch_wait_ms': 0,
 'validate_workers_after_construction': True,
 'preprocessor_pref': 'deepmind',
 'observation_filter': 'NoFilter',
 'compress_observations': False,
 'enable_tf1_exec_eagerly': False,
 'sampler_perf_stats_ema_coef': None,
 'gamma': 0.95,
 'lr': 0.00454119,
 'grad_clip': 40.0,
 'grad_clip_by': 'global_norm',
 'train_batch_size': 1,
 'model': {'_disable_preprocessor_api': False,
  '_disable_action_flattening': False,
  'fcnet_hiddens': [256, 256],
  'fcnet_activation': 'tanh',
  'conv_filters': [[16, [2, 2], 2], [32, [2, 2], 2], [64, [4, 4], 4], [256, [8, 8], 1]],
  'conv_activation': 'relu',
  'post_fcnet_hiddens': [],
  'post_fcnet_activation': 'relu',
  'free_log_std': False,
  'no_final_linear': False,
  'vf_share_layers': True,
  'use_lstm': False,
  'max_seq_len': 20,
  'lstm_cell_size': 256,
  'lstm_use_prev_action': False,
  'lstm_use_prev_reward': False,
  '_time_major': False,
  'use_attention': False,
  'attention_num_transformer_units': 1,
  'attention_dim': 64,
  'attention_num_heads': 1,
  'attention_head_dim': 32,
  'attention_memory_inference': 50,
  'attention_memory_training': 50,
  'attention_position_wise_mlp_dim': 32,
  'attention_init_gru_gate_bias': 2.0,
  'attention_use_n_prev_actions': 0,
  'attention_use_n_prev_rewards': 0,
  'framestack': True,
  'dim': 84,
  'grayscale': False,
  'zero_mean': True,
  'custom_model': None,
  'custom_model_config': {},
  'custom_action_dist': None,
  'custom_preprocessor': None,
  'encoder_latent_dim': None,
  'always_check_shapes': False,
  'lstm_use_prev_action_reward': -1,
  '_use_default_native_models': -1},
 'optimizer': {},
 'max_requests_in_flight_per_sampler_worker': 2,
 '_learner_class': None,
 '_enable_learner_api': False,
 'explore': True,
 'exploration_config': {'type': 'EpsilonGreedy',
  'initial_epsilon': 1.0,
  'final_epsilon': 0.01,
  'epsilon_timesteps': 9000000,
  'warmup_timesteps': 900000},
 'algorithm_config_overrides_per_module': {},
 'policy_map_capacity': 100,
 'policy_mapping_fn': <function ray.rllib.algorithms.algorithm_config.AlgorithmConfig.DEFAULT_POLICY_MAPPING_FN(aid, episode, worker, **kwargs)>,
 'policies_to_train': None,
 'policy_states_are_swappable': False,
 'observation_fn': None,
 'count_steps_by': 'env_steps',
 'input_config': {},
 'actions_in_input_normalized': False,
 'postprocess_inputs': False,
 'shuffle_buffer_size': 0,
 'output': None,
 'output_config': {},
 'output_compress_columns': ['obs', 'new_obs'],
 'output_max_file_size': 67108864,
 'offline_sampling': False,
 'evaluation_interval': 100,
 'evaluation_duration': 1,
 'evaluation_duration_unit': 'episodes',
 'evaluation_sample_timeout_s': 180.0,
 'evaluation_parallel_to_training': False,
 'evaluation_config': {'explore': False,
  'env': 'simharness2.environments.reactive_bench_sarl.ReactiveHarness',
  'env_config': {'sim': <simfire.sim.simulation.FireSimulation at 0x7fa7e4c44dc0>,
   'movements': ['up', 'down', 'left', 'right'],
   'interactions': ['fireline'],
   'attributes': ['fire_map', 'bench_fire_map', 'bench_fire_map_final'],
   'normalized_attributes': [],
   'agent_speed': 4,
   'harness_analytics_partial': functools.partial(<class 'simharness2.analytics.harness_analytics.ReactiveHarnessAnalytics'>, sim_analytics_partial=functools.partial(<class 'simharness2.analytics.simulation_analytics.FireSimulationAnalytics'>, agent_analytics_partial=functools.partial(<class 'simharness2.analytics.agent_analytics.ReactiveAgentAnalytics'>, movement_types=['up', 'down', 'left', 'right'], interaction_types=['fireline'], save_history=True), save_history=True)),
   'reward_cls_partial': functools.partial(<class 'simharness2.rewards.base_reward.BenchFirstRewardV3'>),
   'initial_agent_pos': [64, 0],
   'randomize_initial_agent_pos': False,
   'benchmark_sim': <simfire.sim.simulation.FireSimulation at 0x7fa7e4c44eb0>,
   'action_space_partial': functools.partial(<class 'gymnasium.spaces.discrete.Discrete'>),
   'is_evaluation_env': True,
   'evaluation_duration': 1}},
 'off_policy_estimation_methods': {},
 'ope_split_batch_by_episode': True,
 'evaluation_num_workers': 1,
 'always_attach_evaluation_results': False,
 'enable_async_evaluation': False,
 'in_evaluation': False,
 'sync_filters_on_rollout_workers_timeout_s': 60.0,
 'keep_per_episode_custom_metrics': False,
 'metrics_episode_collection_timeout_s': 60.0,
 'metrics_num_episodes_for_smoothing': 100,
 'min_time_s_per_iteration': None,
 'min_train_timesteps_per_iteration': 0,
 'min_sample_timesteps_per_iteration': 1000,
 'export_native_model_files': False,
 'checkpoint_trainable_policies_only': False,
 'logger_creator': None,
 'logger_config': {'type': ray.tune.logger.tensorboardx.TBXLogger,
  'logdir': '/nfs/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07'},
 'log_level': 'INFO',
 'log_sys_usage': True,
 'fake_sampler': False,
 'seed': 2000,
 'ignore_worker_failures': False,
 'recreate_failed_workers': False,
 'max_num_worker_restarts': 1000,
 'delay_between_worker_restarts_s': 60.0,
 'restart_failed_sub_environments': False,
 'num_consecutive_worker_failures_tolerance': 100,
 'worker_health_probe_timeout_s': 60,
 'worker_restore_timeout_s': 1800,
 'rl_module_spec': None,
 '_enable_rl_module_api': False,
 '_AlgorithmConfig__prior_exploration_config': None,
 '_tf_policy_handles_more_than_one_loss': False,
 '_disable_preprocessor_api': False,
 '_disable_action_flattening': False,
 '_disable_execution_plan_api': True,
 '_disable_initialize_loss_from_dummy_batch': False,
 'simple_optimizer': False,
 'policy_map_cache': -1,
 'worker_cls': -1,
 'synchronize_filters': -1,
 'replay_sequence_length': None,
 'target_network_update_freq': 3000,
 'replay_buffer_config': {'type': ray.rllib.utils.replay_buffers.multi_agent_prioritized_replay_buffer.MultiAgentPrioritizedReplayBuffer,
  'prioritized_replay': -1,
  'capacity': 800,
  'prioritized_replay_alpha': 0.6,
  'prioritized_replay_beta': 0.4,
  'prioritized_replay_eps': 1e-06,
  'replay_sequence_length': 1,
  'worker_side_prioritization': False,
  '_enable_replay_buffer_api': True,
  'storage_unit': 'episodes'},
 'num_steps_sampled_before_learning_starts': 3000,
 'store_buffer_in_checkpoints': False,
 'lr_schedule': None,
 'adam_epsilon': 1e-08,
 'tau': 1.0,
 'num_atoms': 10,
 'v_min': -5,
 'v_max': 5,
 'noisy': True,
 'sigma0': 0.5,
 'dueling': True,
 'hiddens': [256],
 'double_q': True,
 'n_step': 4,
 'before_learn_on_batch': None,
 'training_intensity': None,
 'td_error_loss_fn': 'huber',
 'categorical_distribution_temperature': 1.0,
 '__stdout_file__': None,
 '__stderr_file__': None,
 'input': 'sampler',
 'policies': {'default_policy': [None, None, None, None]},
 'callbacks': simharness2.callbacks.render_env.RenderEnv,
 'create_env_on_driver': False,
 'custom_eval_function': None,
 'framework': 'torch',
 'num_cpus_for_driver': 1,
 'num_workers': 8}

In [9]:
best_result.checkpoint

Checkpoint(local_path=/data/lslab2/fireline/simharness/experiments/2023-11-13_02-09-07/DQN/DQN_simharness2.environments.reactive_bench_sarl.ReactiveHarness_b015d_00000_0_2023-11-13_02-09-35/checkpoint_002000)

## Metric Extraction: Access the entire history of reported metrics from a `Result` as a pandas DataFrame

In [10]:
trial_df = best_result.metrics_dataframe
trial_df

,episode_reward_max,episode_reward_min,episode_reward_mean,episode_len_mean,episodes_this_iter,num_faulty_episodes,num_healthy_workers,num_in_flight_async_reqs,num_remote_worker_restarts,num_agent_steps_sampled,...,sampler_results/sampler_perf/mean_env_wait_ms,sampler_results/sampler_perf/mean_env_render_ms,sampler_results/connector_metrics/ObsPreprocessorConnector_ms,sampler_results/connector_metrics/StateBufferConnector_ms,sampler_results/connector_metrics/ViewRequirementAgentConnector_ms,info/learner/default_policy/num_grad_updates_lifetime,info/learner/default_policy/diff_num_grad_updates_vs_sampler_policy,info/learner/default_policy/td_error,info/learner/default_policy/mean_td_error,info/learner/default_policy/learner_stats/cur_lr
0,0.018800,-0.001421,0.009498,473.000,8,0,8,0,0,3784,...,56.484904,0.0,0.013953,0.008592,0.292319,237.0,236.0,[2.5978818 2.4390802 2.3723457 2.3090692 2.209...,2.208864,0.004541
1,0.039763,-0.001421,0.013479,502.250,8,0,8,0,0,8036,...,51.311993,0.0,0.027834,0.008471,0.287330,748.0,747.0,[2.1400468 2.1475449 2.1272686 2.1220808 2.131...,2.060949,0.004541
2,0.039763,-0.001421,0.013020,508.500,8,0,8,0,0,12204,...,47.598176,0.0,0.023195,0.008438,0.309917,1283.0,1282.0,[1.9879694 1.9630047 1.9682696 1.9872032 1.975...,1.922168,0.004541
3,0.039763,-0.001421,0.011559,516.625,8,0,8,0,0,16532,...,45.028516,0.0,0.020766,0.008399,0.304782,1814.0,1813.0,[1.8187584 1.8070619 1.7910447 1.7791526 1.786...,1.765067,0.004541
4,0.039763,-0.001421,0.010791,589.500,8,0,8,0,0,23580,...,42.372892,0.0,0.019268,0.008430,0.303046,2355.0,2354.0,[1.629683 1.6341802 1.6071498 1.6297677 1.621...,1.607733,0.004541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.027961,-2.583333,-0.193267,585.000,8,0,8,0,0,9692776,...,29.363787,0.0,0.020152,0.009940,0.340175,431970.0,431969.0,[1.6556647 2.022317 0.94816333 1.2762998 0...,1.241609,0.004541
1996,0.027961,-2.583333,-0.193025,570.440,8,0,8,0,0,9697936,...,29.364636,0.0,0.020316,0.009957,0.340793,431989.0,431988.0,[1.1320169 1.6363213 1.11244 1.2276521 1.196...,1.238810,0.004541
1997,0.027961,-2.583333,-0.192776,548.200,8,0,8,0,0,9701400,...,29.365778,0.0,0.020834,0.010029,0.342409,432278.0,432277.0,[1.0040582 0.9908404 1.0138751 1.0076185 1...,0.978784,0.004541
1998,0.018906,-2.583333,-0.194096,536.680,8,0,8,0,0,9704832,...,29.367018,0.0,0.021192,0.010011,0.342917,432835.0,432834.0,[0.9331094 0.924043 0.9329286 0.91533715 0...,0.921431,0.004541
1999,0.018906,-2.583333,-0.194426,520.680,8,0,8,0,0,9708168,...,29.368646,0.0,0.020466,0.010177,0.346239,433122.0,433121.0,[1.0783982 0.8185965 1.4144962 2.2208886 0...,1.274255,0.004541

In [11]:
METRIC_COLUMNS = [
    "episodes_total",
    "training_iteration",
    "episode_reward_mean", 
    "custom_metrics/burn_rate_reduction_mean", 
    "custom_metrics/timesteps_saved_mean", 
    "custom_metrics/area_saved_mean"
]

In [12]:
metrics_df = trial_df[METRIC_COLUMNS].set_index("training_iteration")

In [13]:
# Truncate metrics to omit episodes AFTER 13496 (after the forgetting begins)
metrics_df = metrics_df[metrics_df["episodes_total"] <= 13496]
metrics_df

,episodes_total,episode_reward_mean,custom_metrics/burn_rate_reduction_mean,custom_metrics/timesteps_saved_mean,custom_metrics/area_saved_mean
training_iteration,,,,,
1,8,0.009498,0.267970,0.000000,9.500000
2,16,0.013479,0.344318,-1.250000,26.562500
3,24,0.013020,0.312959,-0.833333,22.916667
4,32,0.011559,0.297450,-0.625000,17.906250
5,40,0.010791,0.264691,-0.500000,16.175000
...,...,...,...,...,...
1631,13464,0.434984,2.133238,106.480000,740.710000
1632,13472,0.537697,3.062573,84.440000,1214.640000
1633,13480,0.506182,3.031800,57.560000,1213.840000
1634,13488,0.502341,3.021044,57.560000,1204.980000
1635,13496,0.604365,3.360796,72.160000,1400.780000

In [15]:
# NOTE: Must install `hvplot` and `holoviews` for the below line to work. 
# I was just experimenting with the different plotting backends...
pd.options.plotting.backend = 'holoviews'

In [16]:
metrics_df.plot(y="episode_reward_mean")

:Curve   [training_iteration]   (episode_reward_mean)

In [18]:
metrics_df.plot(y="custom_metrics/timesteps_saved_mean")

:Curve   [training_iteration]   (custom_metrics/timesteps_saved_mean)

In [19]:
metrics_df.plot(y="custom_metrics/area_saved_mean")

:Curve   [training_iteration]   (custom_metrics/area_saved_mean)